name: .NET

permissions:
  actions: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      publish:
        description: '是否发布Release'
        required: true
        type: boolean
        default: false
      version:
        description: '输入版本号'
        required: false
        type: string
        default: '1.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore TeleportCommand.csproj

    - name: Build
      run: dotnet build TeleportCommand.csproj --no-restore

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TeleportPlugin
        path: bin/Debug/net9.0/TeleportPlugin.dll

    - name: Upload Release
      if: github.event.inputs.publish == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        files: bin/Debug/net9.0/TeleportPlugin.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
